name: Linux RDP with ngrok

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Desktop & RDP
      run: |
        sudo apt update
        sudo apt install -y xfce4 xfce4-goodies xrdp
        sudo systemctl enable xrdp
        sudo systemctl start xrdp
        echo "rdpuser:Passw0rd123" | sudo chpasswd
        sudo adduser rdpuser sudo

    - name: Download Ngrok
      run: |
        curl -s https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip -o ngrok.zip
        unzip ngrok.zip
        sudo mv ngrok /usr/local/bin

    - name: Setup Ngrok
      run: ngrok authtoken 31ptSxqZonJQK4hnO5XbX5A4nZk_3fTG3JqZKucU8keLrpL4N

    - name: Start Tunnel
      run: |
        nohup ngrok tcp 3389 --log=stdout > ngrok.log &
        sleep 10
        tail -n 20 ngrok.log
