name: Run My Script 24/7

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes run hobe
  workflow_dispatch:          # manual run option

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Script
        run: node index.js   # ekhane apnar main script file name boshaben
